console.log("Understand Number Data Type");
console.log("Simple Integer Number");
let num_a = 56;
console.log("a=",num_a);
console.log("Simple Float Number");
let num_d = 564.45;
console.log("d=",num_d);
console.log("Infinity Number");
let num_b = 1/0;
console.log("b=",num_b);
console.log("Not a Number Nan");
let num_c = "Hello"/3;
console.log("c=",num_c);